version: "3.9"
services:

  spring_server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"

  react_web:
    build: ./web 
    ports:
      - "3000:3000"
    depends_on:
      - "spring_server"
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    tty: true

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sensors
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    volumes:
      - ./mysqldata:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.9.3
    volumes:
      - "./logstash:/app"
    command: logstash -f /app/mysql_elasticsearch.conf
    depends_on:
      - "elasticsearch"
      - "mysql"

  kibana:
    image: kibana:7.9.3
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
